// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:85da7e71-0e41-489b-86d9-0e321d312c4d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_7NYQyzJ8n",
    "aws_user_pools_web_client_id": "3m7j6uotmof1se8ugeg3tlpebk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gkjjw7n7jbcg3gvqb6qtshwvni.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
